name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run tests
        run: |
          pytest -v
      - name: Verify Auto-Sklearn install
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Auto-Sklearn
        run: |
          python -m pip install --upgrade pip
          pip install auto-sklearn==0.15.0
      - name: Run install check
        run: |
          python scripts/check_autosklearn_install.py
